name: Python CI (Lint & Token-Test)

on:
  pull_request:
    branches: [main]  # oder dein Hauptbranch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Run pylint with custom config
        run: |
          pylint --disable=E1101 $(git ls-files '*.py')

      - name: Run only token_test.py
        run: |
          pytest Tests/token_test.py
